AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SEO Solver - AWS Lambda Python Implementation

Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        STAGE: !Ref StageName

Resources:
  # Same DynamoDB tables as TypeScript - shared across implementations
  # Lambda functions to be implemented per workplan

Outputs:
  StackName:
    Value: !Ref AWS::StackName
