AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SEO Solver - AWS Lambda TypeScript Implementation

Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  PageSpeedApiKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: Google PageSpeed Insights API key (optional)
  GoogleClientId:
    Type: String
    Default: ''
    Description: Google OAuth2 Client ID for Search Console API
  GoogleClientSecret:
    Type: String
    Default: ''
    NoEcho: true
    Description: Google OAuth2 Client Secret
  GoogleRedirectUri:
    Type: String
    Default: ''
    Description: Google OAuth2 Redirect URI

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    MemorySize: 256
    Architectures:
      - arm64
    Environment:
      Variables:
        STAGE: !Ref StageName
        SITES_TABLE: !Ref SitesTable
        ISSUES_TABLE: !Ref IssuesTable
        TOKENS_TABLE: !Ref TokensTable
        PAGESPEED_API_KEY: !Ref PageSpeedApiKey
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
        GOOGLE_REDIRECT_URI: !Ref GoogleRedirectUri

Resources:
  # ============================================================
  # API Gateway
  # ============================================================
  SeoSolverApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PATCH
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-API-Key
        MaxAge: 300

  # ============================================================
  # DynamoDB Tables
  # ============================================================
  SitesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub seo-solver-sites-${StageName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: site_id
          AttributeType: S
      KeySchema:
        - AttributeName: site_id
          KeyType: HASH

  IssuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub seo-solver-issues-${StageName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: site_id
          AttributeType: S
        - AttributeName: issue_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: detected_at
          AttributeType: S
      KeySchema:
        - AttributeName: site_id
          KeyType: HASH
        - AttributeName: issue_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: site_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DetectedAtIndex
          KeySchema:
            - AttributeName: site_id
              KeyType: HASH
            - AttributeName: detected_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub seo-solver-tokens-${StageName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ============================================================
  # Lambda Functions
  # ============================================================

  # Health Check
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-health-${StageName}
      Handler: handlers/health.handler
      CodeUri: ./
      Events:
        HealthApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /health
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/health.ts

  # Google OAuth Authentication
  AuthGoogleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-auth-google-${StageName}
      Handler: handlers/auth-google.handler
      CodeUri: ./
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TokensTable
      Events:
        AuthInitiateApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /auth/google
            Method: GET
        AuthCallbackApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /auth/google/callback
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth-google.ts

  # GSC Properties Endpoint
  GscPropertiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-gsc-properties-${StageName}
      Handler: handlers/gsc-properties.handler
      CodeUri: ./
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TokensTable
      Events:
        GscPropertiesApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /gsc/properties
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/gsc-properties.ts

  # GSC URL Inspection Endpoint
  GscInspectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-gsc-inspect-${StageName}
      Handler: handlers/gsc-inspect.handler
      CodeUri: ./
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TokensTable
      Events:
        GscInspectApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /gsc/inspect
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/gsc-inspect.ts

  # Validate Endpoint
  ValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-validate-${StageName}
      Handler: handlers/validate.handler
      CodeUri: ./
      Timeout: 120
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SitesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssuesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TokensTable
      Events:
        ValidateApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /validate
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/validate.ts

  # Sites Endpoints
  SitesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-sites-${StageName}
      Handler: handlers/sites.handler
      CodeUri: ./
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SitesTable
      Events:
        ListSitesApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /sites
            Method: GET
        RegisterSiteApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /sites
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/sites.ts

  # Issues Endpoints
  IssuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-issues-${StageName}
      Handler: handlers/issues.handler
      CodeUri: ./
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IssuesTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !Sub ${IssuesTable.Arn}/index/*
      Events:
        GetIssuesApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /sites/{site_id}/issues
            Method: GET
        UpdateIssueApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref SeoSolverApi
            Path: /issues/{issue_id}
            Method: PATCH
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/issues.ts

  # Scheduled Validation (disabled by default)
  ScheduledValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub seo-solver-scheduled-${StageName}
      Handler: handlers/scheduled.handler
      CodeUri: ./
      Timeout: 300
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SitesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssuesTable
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
            Enabled: false
            Description: Daily SEO validation at 6 AM UTC
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/scheduled.ts

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub https://${SeoSolverApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  SitesTableName:
    Description: DynamoDB Sites table name
    Value: !Ref SitesTable
  IssuesTableName:
    Description: DynamoDB Issues table name
    Value: !Ref IssuesTable
  TokensTableName:
    Description: DynamoDB Tokens table name
    Value: !Ref TokensTable
  HealthEndpoint:
    Description: Health check endpoint
    Value: !Sub https://${SeoSolverApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/health
  GoogleAuthEndpoint:
    Description: Google OAuth initiate endpoint
    Value: !Sub https://${SeoSolverApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/auth/google
